### ISSUE TITLE
Segmentation fault on second call with invalid model

### ISSUE THREAD

**Issue by rmcar17** [iqtree/piqtree#37]
@thomaskf found another case resulting in a segmentation fault. I suspect it's similar to the last one you managed to fix.

```python
from _piqtree2 import iq_build_tree

iq_build_tree(["a","b","c","d"], ["GGCAAT","GACAAT","CATCAT","CATCGG"], "JC+G0", 1) # Throws a RuntimeError like expected
iq_build_tree(["a","b","c","d"], ["GGCAAT","GACAAT","CATCAT","CATCGG"], "JC+G0", 2) # Second call gives a segmentation fault
```

**Comment by thomaskf** [comment]
Thanks @rmcar17 
I have added an extra pair of try and catch to cover the whole scope of each function, to ensure all the run-time exceptions are caught and the output and error buffer are reset. This fix should be able to manage all exceptions coming from any situation and any function and ensure the buffer is reset before quitting the functions.
This issue has been fixed by commit [20a4a40](https://github.com/iqtree/iqtree2/commit/20a4a40cbc98b822fa3200b05e30e3b16b4512ca)

**Comment by rmcar17** [comment]
Thanks @thomaskf will get the changes in once dependabot sends an update

**Comment by rmcar17** [comment]
Resolved in latest submodule update
