### ISSUE TITLE
ENH: python interface to pairwise distance matrix functionality

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#67]
The function takes an alignment and returns a cogent3.evolve.fast_distance.DistanceMatrix

**Comment by rmcar17** [comment]
@thomaskf I'm encountering a bug with the pairwise distance calculation where I'm getting an error: 

```
Number of threads must be 1 for sequential version.
```

Seems like it's trying to use multiple threads for some reason even though it is in sequential mode

**Comment by thomaskf** [comment]
@rmcar17 I have updated the codes. It should work now. Can you please check whether it is okay now?

I could not test it on my MacBook. Perhaps due to the settings on my MacBook, I could not compile the codes into a library with the multithreading option disabled. I will check it later. Sorry for the inconvenience caused, and thanks a lot for your help, Rob!

**Comment by rmcar17** [comment]
Thanks @thomaskf for the fix! I'll get back to implementing the rest of the functionality
